// ─────────────────────────────────────────────────────────────
// TabibNet — Appointment Service (booking, cancel, check-in)
// ─────────────────────────────────────────────────────────────

import { getClient, query } from '../db/pool';
import { config } from '../config';

/**
 * Book an appointment with transaction + SELECT FOR UPDATE
 * to prevent double booking.
 */
export async function bookAppointment(
  patientId: string,
  doctorId: string,
  slotId: string
): Promise<any> {
  const client = await getClient();

  try {
    await client.query('BEGIN');

    // Lock the slot row — prevents concurrent bookings
    const slotResult = await client.query(
      'SELECT * FROM slots WHERE id = $1 AND doctor_id = $2 FOR UPDATE',
      [slotId, doctorId]
    );

    if (slotResult.rows.length === 0) {
      throw new Error('SLOT_NOT_FREE');
    }

    const slot = slotResult.rows[0];

    if (slot.status !== 'FREE') {
      throw new Error('SLOT_NOT_FREE');
    }

    // Mark slot as BOOKED
    await client.query(
      'UPDATE slots SET status = $1 WHERE id = $2',
      ['BOOKED', slotId]
    );

    // Remove any previous cancelled appointment on this slot
    // (the UNIQUE constraint on slot_id would block re-booking otherwise)
    await client.query(
      `DELETE FROM appointments WHERE slot_id = $1 AND status = 'CANCELLED'`,
      [slotId]
    );

    // Create appointment (qr_token auto-generated by DB default)
    const appointmentResult = await client.query(
      `INSERT INTO appointments (patient_id, doctor_id, slot_id, type, status)
       VALUES ($1, $2, $3, 'SCHEDULED', 'BOOKED')
       RETURNING *`,
      [patientId, doctorId, slotId]
    );

    await client.query('COMMIT');

    return appointmentResult.rows[0];
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
}

/**
 * Cancel an appointment (patient-side).
 * Checks cancellation deadline and frees the slot.
 */
export async function cancelAppointment(
  appointmentId: string,
  patientId: string
): Promise<any> {
  const result = await query(
    `SELECT a.*, s.start_datetime FROM appointments a
     JOIN slots s ON s.id = a.slot_id
     WHERE a.id = $1 AND a.patient_id = $2`,
    [appointmentId, patientId]
  );

  if (result.rows.length === 0) {
    throw new Error('NOT_FOUND');
  }

  const appointment = result.rows[0];

  if (appointment.status === 'CANCELLED') {
    throw new Error('ALREADY_CANCELLED');
  }

  // Check cancellation deadline
  const slotTime = new Date(appointment.start_datetime);
  const deadline = new Date(
    slotTime.getTime() - config.CANCEL_DEADLINE_HOURS * 60 * 60 * 1000
  );

  if (new Date() > deadline) {
    throw new Error('CANCEL_DEADLINE_PASSED');
  }

  // Cancel appointment + free slot
  await query('UPDATE appointments SET status = $1 WHERE id = $2', ['CANCELLED', appointmentId]);
  await query('UPDATE slots SET status = $1 WHERE id = $2', ['FREE', appointment.slot_id]);

  return { message: 'Rendez-vous annulé', id: appointmentId };
}

/**
 * Check-in using QR token.
 * Marks appointment as ARRIVED with timestamp.
 */
export async function checkinAppointment(
  appointmentId: string,
  qrToken: string
): Promise<any> {
  const result = await query(
    'SELECT * FROM appointments WHERE id = $1',
    [appointmentId]
  );

  if (result.rows.length === 0) {
    throw new Error('NOT_FOUND');
  }

  const appointment = result.rows[0];

  if (appointment.qr_token !== qrToken) {
    throw new Error('INVALID_TOKEN');
  }

  if (appointment.status === 'ARRIVED') {
    throw new Error('ALREADY_CHECKED_IN');
  }

  const updateResult = await query(
    `UPDATE appointments SET status = 'ARRIVED', checkin_at = now()
     WHERE id = $1 RETURNING *`,
    [appointmentId]
  );

  return updateResult.rows[0];
}

/**
 * Get all appointments for a patient with doctor + slot details.
 */
export async function getPatientAppointments(patientId: string): Promise<any[]> {
  const result = await query(
    `SELECT a.id, a.status, a.type, a.checkin_at, a.qr_token, a.created_at,
            s.start_datetime, s.end_datetime,
            u.full_name AS doctor_name, dp.specialty, dp.clinic_name
     FROM appointments a
     JOIN slots s ON s.id = a.slot_id
     JOIN doctor_profiles dp ON dp.id = a.doctor_id
     JOIN users u ON u.id = dp.user_id
     WHERE a.patient_id = $1
     ORDER BY s.start_datetime DESC`,
    [patientId]
  );

  return result.rows;
}
